### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by wangzeyu135798** [BUPT-GAMMA/CPF#1]
你好：
       我关注你这篇文章很长时间了，感谢你的代码公开分享。
       我在运行代码的时候出现一个问题，似乎是我的optuna模块版本不适合，请问你的optuna使用的哪个版本？
       谢谢。

**Comment by J-cabin** [comment]
Thanks for your question! I added the requirements file, which has detailed version information, including Optuna and other dependencies.

**Comment by wangzeyu135798** [comment]
您好：
&nbsp; &nbsp; &nbsp;关于dgl我还想请教一个问题，根据其版本不同，在使用相同的dgl.Graph创建dgl图的时候，会有两种类型一种是DGLGraph，还有一种是DGLHeteroGraph，请问后者带有Hetero是什么意思？与前者会有不同结果且会对整体实验有影响吗？谢谢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BUPT-GAMMA/CPF"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月6日(星期六) 下午5:15
收件人:&nbsp;"BUPT-GAMMA/CPF"<CPF@noreply.github.com&gt;;
抄送:&nbsp;"天津工业大学王泽宇"<1051533398@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [BUPT-GAMMA/CPF] code question (#1)





 
Thanks for your question! I added the requirements file, which has detailed version information, including Optuna and other dependencies.

**Comment by J-cabin** [comment]
感谢您的提问，Hetero代表异质图，我没有使用这种类型，可能会对实验结果产生影响，所以建议您直接创建DGLGraph类型。




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
