### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by fwithyou** [BUPT-GAMMA/CPF#10]
你好，我想问一下代码的哪个参数是用来设置蒸馏时学生模型属于参数化标签传播（PLP）或者特征变换（FT）或者两者的结合，还有在做知识蒸馏的时候，选用的学生模型和教师模型的基础模型是一致的吗，还是不一致的？

**Comment by YilingY6** [comment]
你好，请问解决了吗，我也是遇到了这个问题

**Comment by fwithyou** [comment]
> 你好，请问解决了吗，我也是遇到了这个问题

你好，还没有得到回复，现在暂时没看这个代码了

**Comment by J-cabin** [comment]
你好，
1. 调整PLP/FT的参数是lr_alpha
2. 做知识蒸馏的时候，教师模型是GNN（GCN, GAT, ...），学生模型是CPF，二者不一致。
