### ISSUE TITLE
Why use idx_no_train

### ISSUE THREAD

**Issue by Chrisable** [BUPT-GAMMA/CPF#11]
When training student models，why use idx_no_train？

```
    if conf['model_name'] == 'PLP':
        loss = my_loss(logp[idx_no_train], cas[-1][idx_no_train]) 
```

**Comment by J-cabin** [comment]
The reason is that the information of Labeled Node has been used as input, which is difficult to supervise. It is recommended that you read the paper carefully to better understand the model and code.
