### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by k-styles** [BUPT-GAMMA/CPF#12]
Hi,
Could you please let me know from where did you download the datasets for your work?
I would like to work with ppi dataset, but I am unable to find it in your format.

**Comment by J-cabin** [comment]
Thank you for following our work, so much time has passed that I forget which code the dataset came from. But you can look through the referenced papers in the paper where the dataset is introduced and you might find what you need.

**Comment by k-styles** [comment]
Hi,
I went through your paper and found out the repo: https://github.com/shchur/gnn-benchmark
(Thought you might wanna know)

**Comment by J-cabin** [comment]
Thanks for your email, good luck!

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Kartik&nbsp;Anand ***@***.***&gt;;
发送时间：2023年4月30日(星期天) 晚上6:21
收件人："BUPT-GAMMA/CPF" ***@***.***&gt;;
抄送："Jiawei ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [BUPT-GAMMA/CPF] About Datasets (Issue #12)
-----------------------------------

 

 
Hi,
 I went through your paper and found out the repo: https://github.com/shchur/gnn-benchmark
 (Thought you might wanna know)
