### ISSUE TITLE
dgl version

### ISSUE THREAD

**Issue by wangzeyu135798** [BUPT-GAMMA/CPF#2]
您好：
     关于dgl我还想请教一个问题，根据其版本不同，在使用相同的dgl.Graph创建dgl图的时候，会有两种类型一种是DGLGraph，还有一种是DGLHeteroGraph，请问后者带有Hetero是什么意思？与前者会有不同结果且会对整体实验有影响吗？谢谢。

**Comment by J-cabin** [comment]
Thank you for your question. Hetero stands for heterogeneous graphs. I did not use this type, which may affect the results of the experiment, so it is recommended that you directly create the DGLGraph type.
