### ISSUE TITLE
有关teacher model---GLP

### ISSUE THREAD

**Issue by xinsheng44** [BUPT-GAMMA/CPF#3]
同学，您好，在我跑GLP这个teacher model时，发现没有这个model，
python train_dgl.py --dataset=cora --teacher=GLP；
此外，我发现代码中有个teacher model---MoNet ，但是您的论文实验结果没有该模型的实验结果。
期待您的解答，非常感谢！

**Comment by J-cabin** [comment]
1. 我们使用的GLP代码来自原作者，由于是tensorflow的，没有整合到我们的仓库中。如需复现，您需要单独运行https://github.com/liqimai/Efficient-SSL。
2. MoNet代码作为例子，供研究人员自行测试除论文外的GNN模型，您也可以选择导入其他的GNN模型，与论文本身无关。
