### ISSUE TITLE
the training of student model

### ISSUE THREAD

**Issue by check-777** [BUPT-GAMMA/CPF#9]
在训练Teacher, 正如你代码的备注一样只是计算labeled node的loss
![image](https://user-images.githubusercontent.com/65898252/144567413-84cf514c-1abb-43b2-a951-5445ad16cb44.png)
复现结果符合文章中结果
![image](https://user-images.githubusercontent.com/65898252/144567711-694aa48a-32e9-4ac7-ad33-f3b0d08901c0.png)
但在训练Student的时候，你备注写的也是在labeled node上面，但是却是在unlabeled nodes上面计算loss
![image](https://user-images.githubusercontent.com/65898252/144567879-953442c7-d7c3-4ecd-ad22-5af955e29a00.png)
我把loss的计算改为labeled node上(idx_train),这与文中的结果十分不符合，甚至降低了teacher model的性能
![image](https://user-images.githubusercontent.com/65898252/144568298-c50dc3b9-6d8f-487e-abf4-86340806fd39.png)
如果按照un_labeled node上计算loss，确实和你文章中的结果相似
![image](https://user-images.githubusercontent.com/65898252/144568666-b6645660-1084-4b55-9a93-66dba3fb0d00.png)
请问是什么原因导致了这个问题，还是我的理解出现了偏差？

**Comment by J-cabin** [comment]
原因是labeled node的信息已经作为输入使用，难以起到监督作用。建议您仔细阅读论文，以便更好地理解模型及代码。

**Comment by check-777** [comment]
好，谢谢您的回答，但建议您修改一下student model那里loss的备注，那里写的是在labeled node上计算loss
